### ISSUE TITLE
crash reloading a reaper project on ArchLinux

### ISSUE THREAD

**Issue by trummerschlunk** [DISTRHO/Cardinal#111] opened 2022-01-10 11:29 UTC
Thanks for your great work!!

On reaper/linux/arch cardinal works as far as I could test, but I cannot reload projects saved with a cardinal instance. Reaper crashes on load.

I am sorry for not providing logs. Where would they be?

Thanks!

**Comment by falkTX** [comment] 2022-01-10 11:32
See if the github action builds fix the issue, other people running arch have reported crashes that do not appear when using the pre-compiled builds.
Let me know how they work.

**Comment by trummerschlunk** [comment] 2022-01-10 12:21
Thanks, will try...

**Comment by jypma** [comment] 2022-01-10 13:10
I can confirm the issue, and the workaround works for me (arch linux).

Cardinal built using [cardinal-git](https://aur.archlinux.org/packages/cardinal-git/) from AUR:
- Using carla 2.4.1-2, saving a setup with Cardinal works, but loading it again crashes Carla.

Cardinal built from github actions saves and loads fine in Carla.

Is the mysterious `SYSDEPS=true` perhaps the cause behind it? The AUR build doesn't seem to do anything fancy otherwise.

By the way, the built-it "Load" and "Save" inside Cardinal itself are no-ops for me. Is that as intended?

**Comment by falkTX** [comment] 2022-01-10 23:42
Just tried `SYSDEPS=true` here, no crash on save and loading with Carla.

So I suspect crash comes from somewhere else.

**Comment by trummerschlunk** [comment] 2022-01-20 19:01
How do you build/install from github actions (on arch)? I really tried to figure it out, but I find nothing... Sorry, probably a very noob question.

Thank you

**Comment by jypma** [comment] 2022-01-20 19:08
1. Pick the top link on the [github actions](https://github.com/DISTRHO/Cardinal/actions) page. That'll be the most recent commit.
2. On that page (e.g. [here](https://github.com/DISTRHO/Cardinal/actions/runs/1720273751#artifacts)), scroll all the way down to "Artifacts"
3. Pick the artifact that matches your architecture (on arch linux, that's probably the one with `x86_64` in its name)
4. Extract that anywhere in your home folder
5. Place symlinks to the `.lv2` directories from `~/.lv2`, and make sure `~/.lv2` is in `LV2_PATH` (although I think it is, by default)

**Comment by trummerschlunk** [comment] 2022-01-20 19:18
Thanks indeed :)

**Comment by trummerschlunk** [comment] 2022-02-17 16:39
So yes, falkTX, same behaviour as in this issue with the arch packaged version here.
The latest version from github actions works fine with reaper and bitwig as vst and lv2.

**Comment by falkTX** [comment] 2022-02-17 16:44
so we need someone to build cardinal with `DEBUG=true` and get a backtrace.
is this something you can do?

**Comment by trummerschlunk** [comment] 2022-02-17 16:47
oh my, no. I am a musician (still) ;)

But David, who packaged it for arch should be able to do it... I'll ask him...

**Comment by dvzrv** [comment] 2022-02-17 18:34
I have rebuild cardinal and ardour with additional debug package.

Here is the backtrace of when I'm attempting to load a session with an instance of cardinal in it:
[trace.log](https://github.com/DISTRHO/Cardinal/files/8091249/trace.log)

**Comment by falkTX** [comment] 2022-02-17 23:44
Found the culprit, ArchLinux uses `-D_GLIBCXX_ASSERTIONS` build flag which adds a bunch of assertions on STL classes.
Seems some code is using `std::vector` incorrectly, found at least 2 places where it happens.
See #156 for the dedicated ticket for it.

In the mean time https://github.com/DISTRHO/Cardinal/commit/e9dc1c87b8f30611b9fb07959288c6acca1b577d has a workaround, simply skipping the assertions that trigger the crash.
Since this makes Cardinal behave like all others, I treat it as fixed. even though code should be fixed/improved to handle these STL assertions, it is just that it all comes from code we import (Rack itself)

We should report the issue to VCV, anyone up for that? :)

**Closed by falkTX** 2022-02-17 23:44 UTC
