### ISSUE TITLE
Snandalone Cardinal can not save a session

### ISSUE THREAD

**Issue by cooltehno** [DISTRHO/Cardinal#149] opened 2022-02-16 07:00 UTC
Hello!
Can't save a patches in a standalone version (Ubuntu 20.04, KXStudio repo):
![cardinal_cannot_save](https://user-images.githubusercontent.com/19673308/154212237-20a4faa2-a0d4-42ac-8aaf-d1776c708fc3.gif)

**Comment by dromer** [comment] 2022-02-16 07:19
You mean that this does work for lv2/vst2/vst3?

Otherwise probably a duplicate of https://github.com/DISTRHO/Cardinal/issues/135

**Comment by cooltehno** [comment] 2022-02-16 08:19
@dromer
A duplicate of https://github.com/DISTRHO/Cardinal/issues/135. Thanks!

**Closed** 2022-02-16 08:37 UTC
