### ISSUE TITLE
Manual move of CLAP Folder issue into "...Common Files\CLAP"

### ISSUE THREAD

**Issue by cxbignekoc** [DISTRHO/Cardinal#442] opened 2022-11-29 21:56 UTC
Windows 10
Bitwig 4.4.3

My main CLAP Folder is
`C:\Program Files\Common Files\CLAP\...`

But if i drop Cardinal.clap Folder into \CLAP

An Popup in Cardinal tell me:

**System directory: `C:\Program Files\Common Files\Cardinal` does not exist.**

That is true because it should be the CLAP Folder where to search.

**Questions:**

1. I am not sure if the \CLAP Folder is the Windows Standard, but it works for me, i got some CLAP Plugins into it. If this is a Standard then Cardinal should search the .clap there.
2.  I can add the Cardinal Folder with ease, and it probably will work, but then every Developer will do the same that `C:\Program Files\Common Files\` is the main CLAP Folder. And we need to add every Developer manually to the Plugin Folder in the DAW or the DAW search the whole Common File Folder...

**Comment by falkTX** [comment] 2022-11-30 04:58
The final path should be alike `C:\Program Files\Common Files\CLAP\Cardinal.clap\CardinalSynth.clap` and this is according to CLAP specs (Cardinal only does a special thing with putting 3 plugins inside a single folder, but this is only for having them share the same "resources" folder).

The path `C:\Program Files\Common Files\Cardinal` is the fallback when the local resources folder does not exist (ie, alongside the plugin binary).
Is this missing on CLAP builds?

**Comment by falkTX** [comment] 2023-02-25 14:02
assuming things are working as intended, closing ticket

**Closed by falkTX** 2023-02-25 14:02 UTC
