### ISSUE TITLE
MSHack ping pong - after re opening a project, this module blocks sound 

### ISSUE THREAD

**Issue by offthesky** [DISTRHO/Cardinal#81] opened 2021-12-11 00:52 UTC
steps to repro: load any noise maker module. run it through the mshack ping pong. save your project. reopen your project. notice no sound, until you open up the cardinal window.

finding this in win 10 x64 with c459ab94 (reaper/ableton)

here's a test patch:
[mshack ping pong no worky after reopen.zip](https://github.com/DISTRHO/Cardinal/files/7696127/mshack.ping.pong.no.worky.after.reopen.zip)

**Comment by falkTX** [comment] 2021-12-14 22:32
I am not able to reproduce this in macOS using FLStudio, but didnt try your patch in particular.

**Comment by offthesky** [comment] 2021-12-15 06:08
for me it only seems to occur when the filter is on lp or bp modes.

**Comment by dromer** [comment] 2022-03-30 19:41
@offthesky have you tried this with any of the recent builds? There have been a lot of improvements since last you tried.

**Comment by offthesky** [comment] 2022-03-30 20:55
still happening x86/x64 (both reaper/ableton) win10 w the latest build build #918: Commit [f5ca52b]

**Comment by offthesky** [comment] 2022-04-01 21:41
also fwiw i use veeseevst a lot and the mshack delays in that port dont exhibit any issue. not sure how the code changed when it was adapted to cardinal but perhaps maybe therein lies an answer...

**Comment by dromer** [comment] 2022-04-01 21:57
Veeseevst is based on old 0.6.x code and the included MscHack is also from that era, so I bet there are a _lot_ of changes across the board, really can't very well compare any of this.

**Comment by offthesky** [comment] 2022-04-02 05:17
have u taken a look at the code?  maybe u can figure it out?

**Comment by falkTX** [comment] 2022-05-14 21:27
I can see the issue, happens only when there is no UI visible when project is loaded.
The filter cutoff does not get set in that case, will push a fix shortly.

**Comment by falkTX** [comment] 2022-05-14 22:50
Fixed in c580405fa201846adcc953a1e351dc5c55cae5dc

**Closed by falkTX** 2022-05-14 22:50 UTC
Labels: good first issue, help wanted
