### ISSUE TITLE
CardinalFX VST Issue

### ISSUE THREAD

**Issue by LOoLe2** [DISTRHO/Cardinal#538] opened 2023-06-06 18:50 UTC
Hi, I've tried the CardinalFX VST version. I'm using Ableton and I am using a Mac. There is an issue which makes it hard working with the plug-in. Every time if I touch the cardinal's window I have to click back to Ableton's window again to be able to play or pause the audio which is too often. Anyone else having the same issue? Is there any way to fix it?

**Comment by dromer** [comment] 2023-06-06 18:55
This is because we want keyboard focus to be on the plugin. So that you can search for modules and enter values etc.

Some DAWs can configure if/how a plugin can get this focus, but I don't know anything about Ableton and if it has a setting for this as well.

Usually the problem is the other way around: people are not able to type in the plugin without the DAW starting/stopping transport.

**Comment by LOoLe2** [comment] 2023-06-07 15:36
I see, i will look if I can change it in the settings, thank you.

**Comment by falkTX** [comment] 2023-08-28 07:42
This is a duplicate of #304 which is the meta-issue for all things regarding keyboard input.
anything discussion related to keyboard not working should be moved there.
I have pinned the issue so it is easier to find

**Closed by falkTX** 2023-08-28 07:42 UTC
