### ISSUE TITLE
e340 cloud

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#341] opened 2022-07-31 20:07 UTC
Cloud generator is crashing app in Ableton live 11 Mac Catalina Au & vat 
Thanks

**Comment by falkTX** [comment] 2022-11-30 09:50
I cant reproduce it, was this fixed in 22.11 as well? please confirm, thanks

**Comment by dromer** [comment] 2023-10-25 05:19
@steveparkerdj please confirm this issue with the latest release as well :)

**Comment by dromer** [comment] 2024-08-28 23:53
Lack of feedback so assuming this is fixed.

**Closed by dromer** 2024-08-28 23:53 UTC
