### ISSUE TITLE
No keyboard input in reaper, Vst3 crashes reaper

### ISSUE THREAD

**Issue by TheGuyWhoo** [DISTRHO/Cardinal#32] opened 2021-10-29 18:27 UTC
-Keyboard input doesn't work at all, only mouse input. (I thought this was just a matter of it not being supported yet at first, but realised it works in Carla standalone. It also works within carla vst.)

-Vst3 crashes reaper, lv2 and vst loads fine.

-In ShapeMaster from MindMeld, when you change tabs at the top the length knob disappears and you have to copy and paste the instance of Cardinal to get it back, or close and reopen the project. This happens within Carla as well.

If there's a way to supply logs for these issues I'd be happy to do that, just tell me how.

**Comment by falkTX** [comment] 2021-10-29 18:30
Carla has a logs tab where prints from the plugin will appear.

For the VST3 version, it is expected that things do not work, VST3 is still experimental.

As a serious note, please report 1 issue per ticket.
We are meant to have separate discussions per each individual issue, and then we close the tickets when a specific issue is fixed.

**Comment by MarcBoule** [comment] 2021-11-04 13:26
`-In ShapeMaster from MindMeld, when you change tabs at the top the length knob disappears and you have to copy and paste the instance of Cardinal to get it back, or close and reopen the project. This happens within Carla as well.`

This is an issue with the MindMeld module, and has recently been fixed, sorry for the inconvenience.

**Comment by falkTX** [comment] 2021-11-04 13:33
> ``
> This is an issue with the MindMeld module, and has recently been fixed, sorry for the inconvenience.

I can confirm this is indeed the case, thanks for the fix up!

And thanks for the great modules btw

**Comment by diimdeep** [comment] 2021-11-05 15:00
> -Keyboard input doesn't work at all, only mouse input. 
You have to Shift+TAB Shift+TAB, and it will work!
macOS Catalina + Reaper v6.34

**Comment by bambax** [comment] 2021-12-28 10:51
The last build has no keyboard input in Reaper for me (Win7, LV2 main). The previous build I used from beginning of Dec. (VST2 Instr) had keyboard input although each key was doubled.

**Comment by falkTX** [comment] 2021-12-28 12:00
you need to hide and show the gui again, then keyboard should work.
I will investigate this into detail later, currently finishing the vst3 suppport

**Comment by bambax** [comment] 2021-12-28 14:59
Keyboard input triggers a bell that I think means "forbidden" in Windows.

If I click the UI button in Reaper (top right corner of the plugin window) and back, it doesn't change anything. Is this what you meant, or is there a way to hid and show the gui from inside the plugin?

**Comment by falkTX** [comment] 2021-12-28 16:15
> If I click the UI button in Reaper (top right corner of the plugin window) and back, it doesn't change anything. Is this what you meant

This is what I meant yes.
At least on macOS that does the trick. So on reaper + windows we need something extra :thinking:

**Comment by bambax** [comment] 2021-12-28 18:21
The other thing pointing to a focus problem is the mouse pointer doesn't change to a cursor when I click on the input field. It seems the input field is invisible to the OS maybe.

**Comment by falkTX** [comment] 2021-12-28 18:27
> The other thing pointing to a focus problem is the mouse pointer doesn't change to a cursor when I click on the input field. It seems the input field is invisible to the OS maybe.

No, this is quite expected.
Mouse cursors are not supported yet in Cardinal, the exception being the resize handle on VST2 that I did as a test.

**Comment by falkTX** [comment] 2022-01-01 00:08
vst3 version no longer crashes reaper, but keyboard input still does not always work.

also there seems to be something weird with the way it handles state. it can grow to be quite large because it gets duplicated many times over. dont know why yet

**Comment by bambax** [comment] 2022-02-08 08:13
Still no luck with keyboard input (Win7, Reaper, LV2) with the latest builds.

(Everything else seems to work fine though, including MIDI in and audio out).

**Comment by TheGuyWhoo** [comment] 2022-02-11 14:36
Have you tried enabling 'send all keyboard input to plugin' in the fx drop down menu at the top of the track fx window and then pressing shift+tab twice?

**Comment by falkTX** [comment] 2022-02-11 14:45
I am closing this ticket since we have many that refer to the same thing.
For vst3 specific issues use #41
For focus/keyboard-input issues use #24

**Closed by falkTX** 2022-02-11 14:45 UTC
