### ISSUE TITLE
Pitchbend on Host MIDI CC module does not work

### ISSUE THREAD

**Issue by rafaelferreiraql** [DISTRHO/Cardinal#193] opened 2022-03-16 01:38 UTC
When using VSTi(2) Cardinal on Reaper on Win8 (not sure about VST3 or VST2), the default Pitch bend output in _Host MIDI CC_, well, does not output anything. Note that Pitch bending on the regular _Host MIDI_ module works as normal.

**Comment by falkTX** [comment] 2022-03-16 01:39
is this with 22.03 release or one of the latest builds?
I think this is already fixed on the latest ones.

**Comment by rafaelferreiraql** [comment] 2022-03-16 01:53
Oh, I'm using the stable 22.02 release. Great to know that's been worked on.

**Comment by falkTX** [comment] 2022-03-17 19:15
Can you try the new builds from https://github.com/DISTRHO/Cardinal/actions/workflows/build.yml ?
Would be great to have confirmation that it really works now, thanks!

**Comment by rafaelferreiraql** [comment] 2022-03-18 16:11
Embarassingly, I do not know how to run Actions.

**Comment by falkTX** [comment] 2022-03-18 16:30
no worries, you can use this link https://github.com/DISTRHO/Cardinal/suites/5702890893/artifacts/188019631
still valid for a few days

**Comment by rafaelferreiraql** [comment] 2022-03-19 15:02
Sorry for the delay!

It seems like Host MIDI CC's pitchbend is still broken.

**Comment by falkTX** [comment] 2022-03-21 12:49
I tested this myself just now, and cant reproduce. I mean, it is working fine for me.
Generating and sending some midi pitchbend events to cardinal I see them in polyscope. And the other way around too, some lfo into midi-cc pitchbend input, checked then externally by a midi monitor tool

PS: Rack 2.1 changed how module movement works, ctrl+drag does nothing now.

**Comment by dromer** [comment] 2022-04-09 15:38
I only see an issue with the VST3 (nothing happening). Works fine with VST2 and LV2 (all variants).

**Comment by MrJC11** [comment] 2022-05-17 07:47
I can confirm that with Cardinal v22.05 and while using Reaper v6.57, I too am getting this issue. In fact, no CC outputs work, and no channel pressure.

**Comment by falkTX** [comment] 2022-05-17 08:59
> I can confirm that with Cardinal v22.05 and while using Reaper v6.57, I too am getting this issue. In fact, no CC outputs work, and no channel pressure.

For VST3 only right? The VST2 variant works fine afaik

**Comment by falkTX** [comment] 2022-06-20 22:50
VST3 implementation has been done in efa1eb8a6aa8ec4b0c4ed9f235f024b5945227e6
Closing ticket.

**Closed by falkTX** 2022-06-20 22:50 UTC
