### ISSUE TITLE
Nightly version is showing up black on new instances.

### ISSUE THREAD

**Issue by scotttswan** [DISTRHO/Cardinal#373] opened 2022-09-08 22:00 UTC
when loading a previous project with a Cardinal instance it loads fine but if i add a new Cardinal instrument/fx it loads up with just a black screen.

Tested on both Reaper and Bitwig.

**Comment by dBiz** [comment] 2022-09-09 09:13
Yep, black screen also here in Cubase 11 and FL, on windows 10

**Comment by dBiz** [comment] 2022-09-09 21:26
I've tried resizing the window and it works ;) 
![image](https://user-images.githubusercontent.com/12683589/189448221-131c511e-58f8-4150-b1d6-4cf1b03ba6a8.png)

**Comment by scotttswan** [comment] 2022-09-09 22:19
Yeah Resizing makes it appear.

**Comment by falkTX** [comment] 2022-09-12 07:46
please try with the latest nightly, thanks

**Comment by dBiz** [comment] 2022-09-12 08:06
Same, I've to resize it ;) but is not a big deal!

**Comment by falkTX** [comment] 2022-09-12 08:18
it is, if the first thing a user sees is a black screen they just assume it is not working.

I am unable to reproduce though, so I need details on what your system and host is.
maybe related to non-integer desktop scale factor/zoom ?

**Comment by dBiz** [comment] 2022-09-12 08:32
I'm trying this on Cubase 11 and FL  ( both the latest version available ), on Windows 10.
Both VST3 and VST2 do the same thing, 
On Cubase seems some plugins have OpenGL issues ....
here's what I Found 
https://helpcenter.steinberg.de/hc/en-us/articles/360017509919-Cubase-11-Using-DPI-unaware-plug-ins-on-Windows

**Comment by falkTX** [comment] 2022-09-12 08:43
Cardinal is high-dpi-aware, so the link details do not matter here.
seems issues are only on Windows from what I can tell..

**Comment by scotttswan** [comment] 2022-09-12 11:17
it could be that in "updated" over the stable release rather than installed from fresh?  i'll check again.

**Comment by fotisandstuff** [comment] 2022-09-13 05:27
> it could be that in "updated" over the stable release rather than installed from fresh? i'll check again.

I made a fresh install of the nightly [d5e6f50a](https://github.com/DISTRHO/Cardinal/suites/8253404471/artifacts/360906611) and the problem persists. Windows 10 x64, Reaper.

**Comment by falkTX** [comment] 2022-09-13 21:29
I was able to replicate the issue, pushed a fix.
Please try with https://github.com/DISTRHO/Cardinal/actions/runs/3048050382 once it becomes available.

**Comment by dBiz** [comment] 2022-09-13 21:49
Now it works ;)

**Comment by fotisandstuff** [comment] 2022-09-13 22:12
Nope, still happens. The weird thing is that it happens the second time I load an instance.

**Comment by falkTX** [comment] 2022-09-13 22:15
> Nope, still happens. The weird thing is that it happens the second time I load an instance.

knowing what the issue was, I find it almost impossible for the issue to still be happening.
double-check that you installed the new build please.

**Comment by falkTX** [comment] 2022-09-13 22:27
just tested the nightly/action/CI builds with a known broken setup and can confirm it does work.

**Closed by falkTX** 2022-09-13 22:27 UTC

**Comment by scotttswan** [comment] 2022-09-13 22:59
can confirm its now working.

**Comment by fotisandstuff** [comment] 2022-09-14 00:43
> > Nope, still happens. The weird thing is that it happens the second time I load an instance.
> 
> knowing what the issue was, I find it almost impossible for the issue to still be happening. double-check that you installed the new build please.

Whoops, you're right. It _was_ my fault. I had accidentally re-installed the previous build. It's all good now, thanks a lot!!!
