### ISSUE TITLE
ChordCV is glitching in Cardinal

### ISSUE THREAD

**Issue by chakravala** [DISTRHO/Cardinal#522] opened 2023-04-06 20:59 UTC
ChordCV by Aaron Static is glitching in Cardinal but not in VCV Rack, the module display is glitching and not settling on a value.

**Comment by dromer** [comment] 2023-04-06 21:12
What do you mean with glitching? I'm trying with some LFOs running into it and for sure the range and speed need to be adjusted, but I don't see any "glitching".

**Comment by chakravala** [comment] 2023-04-06 21:16
For me the display on the ChordCV module is very rapidly switching between many different values, faster than my eyes can keep track of. The other modules from Aaron Static work fine, only ChordCV is glitching.

**Comment by GBaige** [comment] 2023-04-06 21:25
Can confirm. REAPER v6.78, Cardinal VST3 (main) 23.02, Windows 11.
![chordcv](https://user-images.githubusercontent.com/115324169/230496826-940fa3cb-3fb1-43a4-9e22-97791b84bdd3.gif)

**Comment by chakravala** [comment] 2023-04-06 21:43
@GBaige that's similar to what the glitch looks like for me on Reaper 6, Cardinal LV2, Linux 6

**Comment by falkTX** [comment] 2023-04-21 10:17
just wondering.. did the behaviour stop with the latest builds? perhaps also related to LTO

**Comment by chakravala** [comment] 2023-04-21 13:01
Tried building `cardinal-git` on arch linux, but got this error:
```
Cloning into '/home/flow/aur/cardinal-git/src/cardinal/carla'...
fatal: transport 'file' not allowed
fatal: clone of '../carla' into submodule path '/home/flow/aur/cardinal-git/src/cardinal/carla' failed
Failed to clone 'carla'. Retry scheduled
Cloning into '/home/flow/aur/cardinal-git/src/cardinal/dpf'...
fatal: transport 'file' not allowed
fatal: clone of '../dpf' into submodule path '/home/flow/aur/cardinal-git/src/cardinal/dpf' failed
Failed to clone 'dpf'. Retry scheduled
Cloning into '/home/flow/aur/cardinal-git/src/cardinal/carla'...
fatal: transport 'file' not allowed
fatal: clone of '../carla' into submodule path '/home/flow/aur/cardinal-git/src/cardinal/carla' failed
Failed to clone 'carla' a second time, aborting
```
So I can't say whether it's fixed yet.

**Comment by GBaige** [comment] 2023-04-22 20:28
> just wondering.. did the behaviour stop with the latest builds? perhaps also related to LTO

Tested again on REAPER v6.78, Cardinal VST3 (main) a42ca2c, visual glitch not present in this build.

**Comment by falkTX** [comment] 2024-04-13 07:54
@chakravala this is likely no longer an issue with the 24.04 release, please confirm

**Comment by MilesSummers** [comment] 2024-08-05 05:56
On archlinux with cardinal standalone 24.05 I am getting the same glitching

**Comment by dromer** [comment] 2024-08-28 23:51
Only now realized this is a duplicate of https://github.com/DISTRHO/Cardinal/issues/431

**Closed by dromer** 2024-08-28 23:51 UTC
Labels: duplicate
