### ISSUE TITLE
Reaper Win11 x64 rendering issues - HiDPI

### ISSUE THREAD

**Issue by Semiote** [DISTRHO/Cardinal#186] opened 2022-03-08 13:23 UTC
Hi there! Thank you for your effort on a great little project.

Cardinal Commit: 6c82749f2a19dac13af79cb4ecff0c6b0a8845d0 : "Make host audio meters independant from each other"
Reaper version: v6.49/win64 rev 9cce1b
Issue: range of crashes + display corruption issues in Reaper.

LV2 - crashes application on plugin load
![win11-x64-reaper-lv2-crash](https://user-images.githubusercontent.com/96491632/157245785-2445af3d-58ee-43a3-8910-b8bc82c38e09.gif)
VST3: crashes upon click / interaction.
![win11-x64-reaper-vst3-crash](https://user-images.githubusercontent.com/96491632/157245801-c2326b8e-d7f4-4d45-97ae-737ef4227ff9.gif)
VST: Display misrenders and click interaction with drop down boxes misses target. lots of missing visuals.
![win11-x64-reaper-vst-corruption](https://user-images.githubusercontent.com/96491632/157245817-8c34136d-a0e8-4a39-9d77-f2b1a0770f60.gif)

**Comment by falkTX** [comment] 2022-03-08 13:31
That seems like a graphics driver issue.
Using software rendering can likely fix the issue.
https://fdossena.com/?p=mesa/index.frag has a special DLL that we can place on reaper folder (the same dir where reaper.exe lives)
I use this when testing cardinal on a VM, otherwise not all graphics render correctly.

**Comment by falkTX** [comment] 2022-03-08 13:32
That said, the resources are for sure missing, so Cardinal was not installed correctly.

**Comment by Semiote** [comment] 2022-03-08 13:55
Moved the folders from the build artefacts zip into the usual plugin locations, and looking at my file system, the structure looks okay? atleast for the VST3/LV2 versions. VST I moved resources folder and .dll to vstplugins root.

Adding the dll into reaper.. doesn't have appeared to have made any difference for me.

**Comment by MiguelRita** [comment] 2022-03-08 14:20
Is it possible you could change your screen scaling to 100% just to test. I'm having the same issue, and this solves it.

**Comment by Semiote** [comment] 2022-03-08 18:37
Setting it to 100% works! WTB hidpi support.

VST beyond the visual corruption was complaining about finding the resources.. 

![vst-not-loading-resources](https://user-images.githubusercontent.com/96491632/157303255-c124e8b9-aebc-4110-9cfa-653c2c8eefb9.png)

**Comment by dromer** [comment] 2022-03-08 20:35
> VST I moved resources folder and .dll to vstplugins root.

This is incorrect, you should move the entire bundle into your vstplugins root.

**Comment by wpostma** [comment] 2022-03-17 05:35
There is now an installer for windows to help with this.  I do believe I did manually copy this earlier build into the right place and had a similar problem with Bitwig and Cardinal, the similarity is the HIGH DPI 250 DPI nature of my system.
I will retry with one of the later builds that has an installer binary.

**Comment by wpostma** [comment] 2022-03-22 20:28
I am a C++ developer and can set up an environment and try to build cardinal and see what I can see.  COuld use tips on what to look and where to look in the code.   Since this fails in reaper and bitwig I'd also like a suggested minimal VST host to try this out inside.   I can probably debug the bitwig or reaper case, but the less DAW there is in there, if the issue reproduces with a minimal plugin host, the better right?

Both Reaper and Bitwig have a "scale the plugins or don't scale them automatically" option of some sort.  That sort of choice feels like an XY problem to me, belonging to the DAW author's list of "things to do".

I could try this in windows in high dpi in ardour too but I don't have a canonical paid for Ardour build 6.9

**Comment by dromer** [comment] 2022-03-22 20:33
@wpostma you can build your own Ardour of course, since it is open source. Other (more minimal) host to try maybe is Carla?

**Comment by wpostma** [comment] 2022-03-22 20:37
I think I'll use carla.

$ pacman -S --needed base-devel mingw-w64-x86_64-toolchain
...
1 gb of stuff.

Any other stuff building.md doesn't mention in the ## Windows section that I need?

**Comment by wpostma** [comment] 2022-03-25 22:19
Carla on windows is currently non functional, and requires a JACK server to run on Windows.  Which makes it a very poor choice of host on Windows.

**Comment by wpostma** [comment] 2022-03-25 22:22
Latest nightlies that are cross compiled from Linux crash every plugin host I try (VST2.4).

Note that VST3 is not ready to test yet, apparently.

**Comment by dromer** [comment] 2022-03-25 23:53
@wpostma you can test the VST3 just fine, just don't expect anything stable/final at all.

Does the LV2 crash as well?

**Comment by falkTX** [comment] 2022-03-26 00:06
> Carla on windows is currently non functional, and requires a JACK server to run on Windows

this is just untrue.

1. the scanning is broken in 2.4.2, I will do a 2.4.3 soon which has the fix, though there are already nightly builds with the fix included
2. carla does not require jack, dont know where that idea comes from. the cardinal standalone does, but carla can use the native windows sound drivers or even asio. just has to be set up that way in the settings.

it is very hard to debug issues on windows since free/open software tools (like gcc and mingw) cannot produce binaries that are able to be debugged. and windows has a very nasty habit of closing stdout and stderr for GUI applications.
so for my own tests I am not able to set breakpoints or even just print stuff to stdout. seems only way to properly log stuff would be to output to a file, which is seriously annoying...

I will get to this eventually, but development under windows just sucks in general after being used to linux for so long. macOS has its quirks, but mostly still usable.

**Closed** 2022-03-26 17:07 UTC
