### ISSUE TITLE
Sidechain input in bitwig doesn't result in audio coming through in channels 3/4 or above

### ISSUE THREAD

**Issue by scotttswan** [DISTRHO/Cardinal#372] opened 2022-09-07 16:55 UTC
![bitwig](https://user-images.githubusercontent.com/5051553/188935831-3df12733-5474-42ff-aa11-741e55d9aca4.png)
i'm routing audio into Cardinal in bitwig via sidechain which in other plugins results in audio coming through channels 3/4.

With Cardinal i receive no CV,  i can route in via audio channels 1/2 without any problems.

**Comment by falkTX** [comment] 2022-09-07 16:56
what version? the latest unreleased 22.09 are required for this, as it is not working on the latest 22.07 stable release

**Comment by scotttswan** [comment] 2022-09-07 17:18
ahh that will be why as i used the release windows.exe installer

**Comment by scotttswan** [comment] 2022-09-07 17:19
i'll test the unreleased 22.09 tonight

**Comment by scotttswan** [comment] 2022-09-09 22:20
Ok i tested it with the latest nightly release but the sidechain option now doesn't appear in bitwig.

**Comment by robbert-vdh** [comment] 2022-09-10 15:05
I investigated this for a bit, the problem is that Cardinal doesn't use the VST3 busses correctly. It should have four stereo input busses. Instead, it has a single 8 channel (surround?) audio input bus and another one for CV. Bitwig's sidechain input goes to the second (auxiliary) audio bus because that's how VST3 works.

**Comment by dromer** [comment] 2022-09-10 15:12
@robbert-vdh with the 22.09 nightly build?

**Comment by falkTX** [comment] 2022-09-10 15:12
see the nightly builds, this has been corrected there.
22.07 has wrong bus setup, but works fine in the upcoming 22.09

the CV stuff is not a single bus though, each CV is on its own "bus". otherwise we would get 10-speaker surround CV which doesnt make much sense. instead we have (in upcoming 22.09) 10x mono CV ports, along-side the 4x stereo audio buses.

**Comment by robbert-vdh** [comment] 2022-09-10 15:18
@dromer Oh yeah no I was using the 22.07 build from the Arch repos. Only installed it because someone on the Unfa Discord asked about this so I thought I'd investigate.

**Comment by falkTX** [comment] 2022-09-10 15:20
I am not sure the best way to deal with the non 1+2 audio channels though. marking everything 3-8 as sidechain seems wrong, but also seems to be what bitwig expects.

likely bitwig has some fancy way to send sidechain to multi-input plugins, I just dont see it.

**Comment by robbert-vdh** [comment] 2022-09-10 15:25
Yeah in the VST3 model every audio bus is its own self contained audio stream with a specific channel layout, usually stereo. So if you have one main stereo input and three additional ones, you'd expose one main stereo input buss and three auxiliary stereo input busses. That's the same idea as with CLAP: there you'd one `CLAP_AUDIO_PORT_IS_MAIN` stereo audio input port and three additional stereo audio input ports.

Bitwig only supports a single main audio input and a single sidechain audio input per plugin though since very few plugins go beyond that. So you'd only be able to address the main input (going to ports 1 and 2) and the first sidechain input (going to ports 3 and 4). May be worth writing to Bitwig support about additional sidechain inputs though, they have plenty of space on the UI for it but they probably just never added it because there wasn't any need for it.

**Comment by falkTX** [comment] 2022-09-10 15:27
hmm but on cardinal they are not sidechain, is just literally extra audio IO. I changed the ports to mean 4x stereo instead of 1x 8-set just to help hosts, there is and never was any special meaning to these ports since this is a modular environment.

**Comment by robbert-vdh** [comment] 2022-09-10 15:31
In a DAW context they'd be sidechain inputs. The main input is coming from the (likely stereo) track the plugin is inserted on, and the other three inputs will be routed from elsewhere.

**Comment by scotttswan** [comment] 2022-09-12 21:24
still broken in the latest nightly,  without exposing them the way it was done in the stable release there's no option to select "sidechain".

**Comment by falkTX** [comment] 2022-09-13 21:16
I am not keen on changing it back though.
Cardinal with 4x stereo IO makes sense. Only the first stereo pair is set as "main", the others are there but without that "main" flag, which is a valid configuration according to the VST3 spec.
Tagging the extra ports as sidechain seems wrong to me, they are additional IO and not really sidechain.

So I am close the ticket as "wont fix".

**Closed by falkTX** 2022-09-13 21:16 UTC

**Comment by robbert-vdh** [comment] 2022-09-13 21:39
> which is a valid configuration according to the VST3 spec.

A bus must have a bus type, which can be either main or aux: https://steinbergmedia.github.io/vst3_doc/vstinterfaces/structSteinberg_1_1Vst_1_1BusInfo.html#a764af5c5b921de1cab2eca6565ea5d1e (the docs conveniently don't specify whether there may only be a single main bus of a given type, but presumably that's implied)

**Comment by scotttswan** [comment] 2022-09-13 21:48
maybe it could be added to the FX version of cardinal as that's where it would be most useful.

**Comment by falkTX** [comment] 2022-09-13 22:13
> > which is a valid configuration according to the VST3 spec.
> 
> A bus must have a bus type, which can be either main or aux: https://steinbergmedia.github.io/vst3_doc/vstinterfaces/structSteinberg_1_1Vst_1_1BusInfo.html#a764af5c5b921de1cab2eca6565ea5d1e (the docs conveniently don't specify whether there may only be a single main bus of a given type, but presumably that's implied)

right, sorry, I miswrote.
I meant it has only "default active" on the 1st IO, the other ones dont have that. but they are all main buses.

**Comment by scotttswan** [comment] 2022-09-13 23:11
i don't know if there are other DAWs that have this problem but with whatever the current stable release had set the sidechain option appeared in bitwig but there was nothing received within cardinal itself.

Current settings in the nightly dont give any option for sidechaining and that option is the only way to get more than tracks 1/2 audio inputs into a vst in bitwig.

Coming from Reaper its quite limiting but the modulation option in bitwig opened up a whole new world.

**Comment by falkTX** [comment] 2022-09-14 00:24
> maybe it could be added to the FX version of cardinal as that's where it would be most useful.

I actually quite like this idea.
but I am afraid of introducing this and breaking existing projects. not all hosts (or plugin formats) handle sidechain properly.
so it is not something to try in the next 22.09 release at least

**Comment by falkTX** [comment] 2022-10-26 16:00
Best would be to try the clap version (the recently enabled "main" variant), though windows build is broken at the moment

**Comment by trevormeier** [comment] 2022-10-26 21:22
I've tried out the latest nightly - it's working for me! Thanks for the tip
