### ISSUE TITLE
Cardinal will not run...

### ISSUE THREAD

**Issue by RossoRacer** [DISTRHO/Cardinal#342] opened 2022-08-01 10:55 UTC
...in macOS Monterey 12.5 using Logic Pro 10.7.4 as you cannot get it past the plugin validation.

**Comment by dromer** [comment] 2022-08-01 11:45
I think this is a duplicate of your own ticket -> https://github.com/DISTRHO/Cardinal/issues/335

Please don't spam the tickets with the same issue over and over.

**Comment by armandvedel** [comment] 2022-08-01 13:48
FWIW I am running Cardinal in Logic 10.7.4. Didn't have any validation problems

**Comment by falkTX** [comment] 2022-08-01 14:03
yeah, duplicate tickets are worthless.
it wont get fixed faster if you spam the project with the same request over and over, actually has the opposite effect as it produces more stuff to clean up and close.

**Closed by falkTX** 2022-08-01 14:03 UTC

**Comment by RossoRacer** [comment] 2022-08-01 18:41
I was trying to be helpful with system information. not spam.

**Comment by falkTX** [comment] 2022-08-01 18:42
then add that info to the already existing ticket, thanks.

**Comment by falkTX** [comment] 2022-08-01 18:44
basically, 1 ticket per issue (independent of host/daw)
