### ISSUE TITLE
Notes playing constantly when hitting multiple keys on MIDI keyboard

### ISSUE THREAD

**Issue by andynameistaken** [DISTRHO/Cardinal#530] opened 2023-04-13 11:18 UTC
- version 23.02
- MIDI keyboard: Arturia Keylab Essential 49
-  Issue:
When I hit multiple keys they play constantly after releasing them. I'm just a beginner, so I don't know much about Cardinal, but on VCV Rack it doesn't happen.

https://user-images.githubusercontent.com/15692002/231742577-282d2fb8-1608-49e0-a910-7f5fddfa87f9.mov

**Comment by GBaige** [comment] 2023-04-13 17:37
- Does this happen inside a DAW? This looks like Cardinal standalone.
- Does this happen when you use virtual MIDI instead of an external controller?
- Does this happen with other modules or in other patches?
- What are the polyphony settings in the Cardinal Host MIDI module?
- What OS?

**Comment by falkTX** [comment] 2023-04-13 19:02
you can see from the video it is CardinalNative under macOS.
I know what the issue is, just no time for fixing that specific part yet.
The problem doesnt happen in the plugin versions, so it is not a priority to fix.

**Comment by falkTX** [comment] 2023-09-02 05:59
This is fixed in 442365e7e8d0c9dda89d1332632f5bfffaf2b614 to be part of 23.09 release

**Closed by falkTX** 2023-09-02 05:59 UTC
