### ISSUE TITLE
Valley Audio Topograph / uGraph

### ISSUE THREAD

**Issue by aenemic** [DISTRHO/Cardinal#152] opened 2022-02-17 11:06 UTC
These two don't seem to work, at least in my case with latest release. No matter the clock source I select, if transport is running or not, no matter the host - they output nothing. Neither with set bpm or with external bpm.

I've tested standalone, synth and fx.

I've tried them in Carla and Ardour, both lv2 and vst3.

**Comment by dromer** [comment] 2022-02-17 11:51
It seems you need to activate `Run` either by external source or pressing the button.

I can see triggers being emitted when I do that.

**Comment by falkTX** [comment] 2022-02-18 01:13
Seems to work fine here.
Take a little to understand, but there are a few options with the right-click menus that make the signal behave as expected, then we can begin to tweak things.
Attached a module selection as demo.

[topograph.vcvs.txt](https://github.com/DISTRHO/Cardinal/files/8093329/topograph.vcvs.txt)

Don't see any bugs here, working as intended.
Closing ticket.

**Closed by falkTX** 2022-02-18 01:13 UTC

**Comment by dromer** [comment] 2022-02-18 01:28
@aenemic please check the patch @falkTX posted (you can copy/paste this into cardinal to try)

In the right click menu you can see some configuration for the module in order to sync like this. We may need to check if the defaults of these modules can be overridden perhaps, so it makes a bit more sense with cardinal host synchronization
